version: '3'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpMyAdmin
    environment:
      - PMA_HOST=bancoMysql
      - PMA_USER=root
      - PMA_PASSWORD=pass2023
      - PMA_PORT=3306
    networks:
      - rede_projeto
    ports:
      - 8080:80

  bancoMysql:
    image: mysql:latest
    container_name: bancoMysql
    ports:
      - 3307:3306
    networks:
      - rede_projeto
    environment:
      - MYSQL_ROOT_PASSWORD=pass2023
      - MYSQL_DATABASE=livraria
      - MYSQL_ROOT_HOST='%'
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  frontend:
    build:
      context: ./webacademy-livros-frontend
      dockerfile: Dockerfile
    image: meufrontend:1.0
    container_name: frontend
    ports:
      - 8000:80
    networks:
      - rede_projeto

  backend:
    build:
      context: ./webacademy-livros-backend
      dockerfile: Dockerfile
    image: meubackend:1.0
    container_name: backend
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h bancoMysql -u root -p${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 10s
      retries: 10
    ports:
      - 4444:4444
    networks:
      - rede_projeto
    volumes:
      - ./webacademy-livros-backend/log:/app/log
    depends_on:
      - bancoMysql

networks:
  rede_projeto:
    driver: bridge
